### 1. 회원가입 (nickname 포함)
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "email": "test1@example.com",
  "password": "Password123!",
  "userRole": "USER",
  "nickname": "테스트코딩"
}

> {%
    client.global.set("auth_token", response.body.bearerToken);
%}